### ISSUE TITLE
Extension Manager possibly affecting iOS scale modes again? (Version 0.2.5)

### ISSUE THREAD

**Issue by GuyCockcroft** [byrobingames/byRobinextensionmanager#1]
I saw a message on the Stencyl thread about previous versions of the extension manager causing some scaling issues on iPhoneX. I have updated Stencyl to version 10331, and am experiencing similar issues (although it was fine on prior versions of Stencyl - sorry I can't be more specific than that though). While I can't guarantee that this is the cause, but I am running out of ideas as to what may be causing the scaling problems (and I'm not a programmer!).

As a result of the bug, the splash screens aren't showing, and the Stencyl blocks that detect the device type also aren't working correctly. It seems to be able to detect the difference between iPhone and iPad, but it can't determine which model of iPhone it is running on.

Thanks for any help!

**Comment by byrobingames** [comment]
Before i we go futher on this..

Did you test it without the extension?

**Comment by GuyCockcroft** [comment]
Ah - sorry for the misleading message. You are right - I disabled it, but it was still messed up. Turns out it was one of the advanced Openfl flags in the editor causing trouble.
I spotted a message in the Extension manager thread on the Stencyl forums, talking about scaling modes, and though I jumped to the wrong conclusion! Sorry about that - thanks for getting back to me.

**Comment by byrobingames** [comment]
Ok no problem.. i Will close the issue
