### ISSUE TITLE
Some extensions require more recent version of gradle when using stencyl b10458

### ISSUE THREAD

**Issue by wcoyote132** [byrobingames/byRobinextensionmanager#2]
https://i.imgur.com/tKEMvr4.png

I haven't tested all of them, but the error above happens when compiling for android. So far it says Unity Ads and Simple Share have this error.

**Comment by byrobingames** [comment]
First the extensions does not use there own version of gradle but it used the gradle version that came with Stencyl

That said.. the error is that the maven repo I uses in gradle build files not have version 3.5.1.

To fix it for now you can change the maven repo to jcenter()

1- go to engine-extension folder
2- Open [EXTENSON_NAME]/dependencies/build.gradle
3- Replace:
```
repositories {
		maven {
			       url "http://repo1.maven.org/maven2/"
		}
}
```
With:
```
repositories {
		jcenter()
		google()
}
```

If I have some time I will make some updates..

**Comment by wcoyote132** [comment]
Ok thank you!
